backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# These lines should *not* be indented
media_folder: "img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://soundgarage.io
display_url: https://soundgarage.io
logo_url: https://www.soundgarage.io/img/logo2.png
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Post" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: md
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", hint: "The title for the blog post, should be short and simple"}
      - {label: "Short Title", name: "shortTitle", widget: "string", hint: "A short title field that will be used in social"}
      - {label: "Description", name: "description", widget: "text", hint: "A short description of the blog post, will be using in social"}
      - {label: "Authored By", name: "authoredBy", widget: "relation", collection: "authors", searchFields: ["fullName"], valueField: "fullName", displayFields: ["fullName"]}
      - {label: "Body", name: "body", widget: "markdown", hint: "Write your blog post here, can be as long as you want with basic formatting."}
      - {label: "Published Date", name: "date", widget: "datetime", hint: "When was this blog post pubished."}
      - {label: "Main Image", name: "thumbnail", widget: "image", required: false, hint: "Provide a main image for the blog post, displayed on homepage or other parts of the site."}
  - name: "authors"
    label: "Authors"
    folder: "author"
    create: true
    extension: md
    format: frontmatter
    identifier_field: fullName
    slug: "{{handle}}"
    fields: 
      - {label: "Name", name: "fullName", widget: "string", required: true}
      - {label: "Handle", name: "handle", widget: "string", required: true, hint: "Provide a handle to use, for example: username"}
      - {label: "Headshot", name: "headShot", widget: "image", allow_multiple: false, required: true, hint: "Headshot to display with your profile, will auto resize to square when displayed"}
      - {label: "Bio", name: "body", widget: "text", required: false, hint: "Write a short bio about yourself to let people know more about you."}
      - {label: "Twitter", name: "twitter", widget: "string", required: false, hint: "Provide your Twitter handle, for example: @user_name"}
      - {label: "Instagram", name: "instagram", widget: "string", hint: "Provide your Instagram handle, for example: user_name"}
      - {label: "Spotify", name: "spotify", widget: "string", hint: "Provide your Spotify handle, for example: user_name"}
      - {label: "Website", name: "website", widget: "string", required: false, hint: "Provide a URL for your website or another website"}
  - name: "settings"
    label: "Site Settings"
    extension: "json"
    editor:
      preview: false
    files:
      - name: "site_configuration"
        label: "Site Configuration"
        file: "_data/settings/site_configuration.json"
        description: "Changing these settings have global impact on the site, only change these if you know what you are doing"
        fields:
          - {label: "Site Name", name: "siteName", widget: "string", required: true}
          - {label: "Site Slogan", name: "siteSlogan", widget: "text", required: false}
          - {label: "Copyright", name: "copyright", widget: "string", required: false}
          - {label: "Site Logo", name: "siteLogo", widget: "image", required: false}
          - {label: "Site Email", name: "siteEmail", widget: "string", required: false}
      - name: "site_styles"
        label: "Site Styles"
        file: "_data/settings/site_styles.json"
        description: "Tweak these settings to change how the site looks without having to touch any css."
        fields:
          - {label: "Border Radius", name: "border-radius", widget: "string", required: true}
          - {label: "Box Shadow", name: "box-shadow", widget: "text", required: false}
          - {label: "Color", name: "color", widget: "string", required: false}
          - {label: "Color Accent", name: "color-accent", widget: "image", required: false}
          - {label: "Color Background", name: "color-bg", widget: "string", required: false}
          - {label: "Color Background Secondary", name: "color-bg-secondary", widget: "string", required: false}
          - {label: "Color Secondary", name: "color-secondary", widget: "string", required: false}
          - {label: "Color Secondary Accent", name: "color-secondary-accent", widget: "string", required: false}
          - {label: "Color Shadow", name: "color-shadow", widget: "string", required: false}
          - {label: "Color Text", name: "color-text", widget: "string", required: false}
          - {label: "Color Text Secondary", name: "color-text-secondary", widget: "string", required: false}
          - {label: "Font Family", name: "font-family", widget: "string", required: false}
          - {label: "Hover Brightness", name: "hover-brightness", widget: "string", required: false}
          - {label: "Justify Important", name: "justify-important", widget: "string", required: false}
          - {label: "Justify Normal", name: "justify-normal", widget: "string", required: false}
          - {label: "Line Height", name: "line-height", widget: "string", required: false}
          - {label: "Card Width", name: "width-card", widget: "string", required: false}
          - {label: "Card Width Medium", name: "width-card-medium", widget: "string", required: false}
          - {label: "Card Width Wide", name: "width-card-wide", widget: "string", required: false}
          - {label: "Content Width", name: "width-content", widget: "string", required: false}
      - name: "social_links"
        label: "Social Links"
        file: "_data/settings/social_links.json"
        description: "Central location for the storage of all social links."
        fields:
          - name: social_links
            label: Social Links
            label_singular: "Social Link"
            widget: list
            fields:
              - {label: "Social Network", name: "social_network", widget: "select", options: [{label: "Facebook", value: "Facebook"},{label: "Twitter", value: "Twitter"},{label: "Instagram", value: "Instagram"},{label: "YouTube", value: "YouTube"},{label: "Pinterest", value: "Pinterest"},{label: "Soundcloud", value: "SoundCloud"},{label: "Twitch", value: "Twitch"},{label: "TikTok", value: "TikTok"}]}
              - {label: "Social Handle", name: "social_handle", widget: "string"}
              - {label: "Social URL", name: "social_url", widget: "string"}
              - {label: "Published", name: "published", widget: "boolean", default: false}
      - name: "primary_navigation"
        label: "Primary Navigation"
        file: "_data/settings/navigation.json"
        description: "Primary Navigation Links"
        fields:
          - name: primary_navigation
            label: Primary Navigation
            label_singular: "Navigation Link"
            widget: list
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Path", name: "path", widget: "string", hint: "Should start with / and be a valid path."}